version: '3.1'

services:
  scale_server:
    image: scale-server
    build: ./scale_server
    restart: always
    environment:
      PORT: 80
    volumes:
      - /scale_server:/usr/src/app/data
      - ~/.env:/usr/src/app/.env


  proxy:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./localweb/build:/var/www/scale
    ports:
      - 80:80
      - 443:443
    links:
      - scale_server
    depends_on: 
      - scale_server
  
